"""
Analyzer Module — Diagnoses WHY prompts are failing.

Takes failing traces from the monitor, clusters them by failure pattern,
and produces a structured diagnostic report using Gemini that guides the optimizer.
"""

import os
import json
import pandas as pd
from dataclasses import dataclass
from pydantic import BaseModel, Field
from google import genai
from google.genai import types
from dotenv import load_dotenv

# Load environment variables
load_dotenv()


@dataclass
class FailureCluster:
    """A group of similar failing queries."""
    category: str               # e.g., "refund_request", "price_match"
    failure_pattern: str        # e.g., "Allows refund without verifying transaction ID"
    example_queries: list[str]  # Representative queries
    example_responses: list[str]  # Bad responses
    expected_behavior: str      # What should have occurred
    count: int                  # Number of instances


@dataclass  
class DiagnosticReport:
    """Complete diagnosis of why a prompt template is underperforming."""
    prompt_id: str
    prompt_version: str
    overall_score: float
    total_failures: int
    failure_clusters: list[FailureCluster]
    improvement_suggestions: list[str]  # Specific suggestions to improve prompt
    original_prompt: str                # Current prompt text


# --- Pydantic Schemas for Gemini Structured JSON Outputs ---

class FailureClusterSchema(BaseModel):
    category: str = Field(
        description="The category of support request, e.g., 'refund_request', 'price_match', 'out_of_scope', 'escalation'"
    )
    failure_pattern: str = Field(
        description="The underlying failure pattern or root cause, e.g., 'Fails to ask for transaction ID before approving refund', 'Answering general programming query instead of politely rejecting'"
    )
    example_queries: list[str] = Field(
        description="List of 1-2 representative queries from the dataset that failed due to this pattern"
    )
    example_responses: list[str] = Field(
        description="The actual failing responses generated by the LLM for those queries"
    )
    expected_behavior: str = Field(
        description="What the assistant SHOULD have done according to proper retail support policies"
    )
    count: int = Field(
        description="Approximate number of queries in the list that match this failure pattern"
    )


class DiagnosticReportSchema(BaseModel):
    failure_clusters: list[FailureClusterSchema] = Field(
        description="Categorized clusters of failures isolated from the logs"
    )
    improvement_suggestions: list[str] = Field(
        description="Highly specific, concrete prompt instructions that would prevent these failures, e.g. 'Must explicitly request and verify a transaction ID before processing any refund requests'"
    )


class FailureAnalyzer:
    def __init__(self):
        api_key = os.getenv("GOOGLE_API_KEY")
        if not api_key or api_key == "your-gemini-api-key":
            raise ValueError("GOOGLE_API_KEY is not set in the environment variables.")
        self.client = genai.Client(api_key=api_key)

    def analyze_failures(
        self,
        failing_spans_df: pd.DataFrame,
        prompt_config: dict,
        overall_score: float
    ) -> DiagnosticReport:
        """
        Analyze failing traces and produce a structured DiagnosticReport.
        
        Args:
            failing_spans_df: DataFrame containing the normalized failing spans
                              (must have 'input', 'output' and optionally 'eval_explanation')
            prompt_config: Dict of the prompt template config from prompts.json
            overall_score: The overall correctness score calculated by the monitor
        """
        prompt_id = prompt_config.get("id", "customer_support")
        prompt_version = prompt_config.get("version", "1.0.0")
        original_prompt = prompt_config.get("system_instruction", "")
        
        total_failures = len(failing_spans_df)
        if total_failures == 0:
            print("No failures to analyze.")
            return DiagnosticReport(
                prompt_id=prompt_id,
                prompt_version=prompt_version,
                overall_score=overall_score,
                total_failures=0,
                failure_clusters=[],
                improvement_suggestions=["Prompt is performing perfectly! No changes needed."],
                original_prompt=original_prompt
            )
            
        print(f"Analyzing {total_failures} failing traces for prompt '{prompt_id}' (v{prompt_version})...")
        
        # Format the failures for Gemini context
        failures_log = []
        for idx, row in failing_spans_df.iterrows():
            explanation = row.get("eval_explanation", "Failed correctness check.")
            failures_log.append({
                "query": row["input"],
                "response": row["output"],
                "reason_for_failure": explanation
            })
            
        # Build prompt for Gemini failure clustering
        analyzer_prompt = f"""
You are an expert prompt engineer and diagnostic agent.
We are analyzing customer support logs where our support assistant failed quality standards.

### Current System Instruction Prompt:
---
{original_prompt}
---

### Failing Interactions Log:
Below is a list of user inputs, model responses, and the auditor's reasons for flagging them as incorrect.
---
{json.dumps(failures_log, indent=2)}
---

### Your Task:
1. Analyze the failing interactions and group/cluster them by failure category and root-cause pattern.
2. For each cluster, extract representative examples of bad queries and bad replies, outline what correct behavior looks like, and calculate how many instances match.
3. Write highly specific, actionable prompt improvements (like new constraints, examples, or policies to inject into the system instructions) that will directly eliminate these failure clusters.

Format your response as a structured JSON object matching the requested schema.
"""

        try:
            # Query Gemini using the structured Pydantic schema
            response = self.client.models.generate_content(
                model="gemini-2.5-flash",
                contents=analyzer_prompt,
                config=types.GenerateContentConfig(
                    response_mime_type="application/json",
                    response_schema=DiagnosticReportSchema,
                    temperature=0.2  # Low temperature for analytical precision
                )
            )
            
            # Parse response JSON
            report_data = json.loads(response.text)
            
            # Convert JSON schemas to FailureCluster dataclass list
            clusters = []
            for cluster_json in report_data.get("failure_clusters", []):
                clusters.append(
                    FailureCluster(
                        category=cluster_json.get("category"),
                        failure_pattern=cluster_json.get("failure_pattern"),
                        example_queries=cluster_json.get("example_queries", []),
                        example_responses=cluster_json.get("example_responses", []),
                        expected_behavior=cluster_json.get("expected_behavior"),
                        count=cluster_json.get("count", 0)
                    )
                )
                
            improvement_suggestions = report_data.get("improvement_suggestions", [])
            
            # Assemble full DiagnosticReport
            report = DiagnosticReport(
                prompt_id=prompt_id,
                prompt_version=prompt_version,
                overall_score=overall_score,
                total_failures=total_failures,
                failure_clusters=clusters,
                improvement_suggestions=improvement_suggestions,
                original_prompt=original_prompt
            )
            
            print("✅ Successfully generated failure diagnostic report!")
            print(f"Isolated {len(clusters)} failure clusters:")
            for c in clusters:
                print(f" - [{c.category}] ({c.count} cases): {c.failure_pattern}")
                
            return report
            
        except Exception as e:
            print(f"❌ Error during Gemini failure analysis: {e}")
            raise e
