"""
Prompt Optimizer Module — Programmatically optimizes prompts using Gemini.

Takes failure analysis results (DiagnosticReport) and the original baseline prompt,
and generates three distinct optimization prompt variants (conservative, moderate, aggressive).
"""

import os
import json
from typing import List
from pydantic import BaseModel, Field
from google import genai
from google.genai import types
from dotenv import load_dotenv

from src.agent.analyzer import DiagnosticReport

# Load environment variables
load_dotenv()


class PromptParametersSchema(BaseModel):
    temperature: float = Field(description="Model temperature, e.g. 0.3")
    max_output_tokens: int = Field(description="Max output tokens, e.g. 1024")


class PromptVariantSchema(BaseModel):
    id: str = Field(
        description="Unique ID for the variant, e.g. customer_support_v1, customer_support_v2, customer_support_v3"
    )
    version: str = Field(
        description="Updated version string, e.g. 1.1.0-v1, 1.1.0-v2, 1.1.0-v3"
    )
    strategy: str = Field(
        description="Description of the strategy used ('v1_conservative', 'v2_moderate', 'v3_aggressive')"
    )
    system_instruction: str = Field(
        description="The complete new system instruction text for the prompt"
    )
    model: str = Field(
        description="Model to use, e.g., 'gemini-2.5-flash'"
    )
    parameters: PromptParametersSchema = Field(
        description="Model parameters containing temperature and max_output_tokens"
    )


class PromptVariantsResponseSchema(BaseModel):
    variants: List[PromptVariantSchema] = Field(
        description="The three distinct prompt variants generated by the optimizer"
    )


class PromptOptimizer:
    def __init__(self):
        api_key = os.getenv("GOOGLE_API_KEY")
        if not api_key or api_key == "your-gemini-api-key":
            raise ValueError("GOOGLE_API_KEY is not set in the environment variables.")
        self.client = genai.Client(api_key=api_key)

    def optimize_prompt(self, report: DiagnosticReport) -> List[dict]:
        """
        Optimize the prompt based on the DiagnosticReport.
        
        Args:
            report: DiagnosticReport from FailureAnalyzer containing failure clusters
                   and improvement suggestions.
                   
        Returns:
            A list of 3 prompt variant dictionaries ready for shadow evaluation.
        """
        print(f"Generating optimized prompt variants for prompt '{report.prompt_id}'...")
        
        # Format the failure clusters and suggestions for the prompt
        clusters_str = ""
        for i, cluster in enumerate(report.failure_clusters):
            clusters_str += f"\n- Failure Cluster {i+1} [{cluster.category}]: {cluster.failure_pattern}\n"
            clusters_str += f"  * Bad Query Example: \"{cluster.example_queries[0] if cluster.example_queries else 'N/A'}\"\n"
            clusters_str += f"  * Bad Response Example: \"{cluster.example_responses[0][:200] if cluster.example_responses else 'N/A'}...\"\n"
            clusters_str += f"  * Expected Behavior: \"{cluster.expected_behavior}\"\n"

        suggestions_str = "\n".join([f"- {sug}" for sug in report.improvement_suggestions])

        optimizer_prompt = f"""
You are an elite LLM system prompt engineer. Your task is to take an underperforming system instruction prompt, analyze its failures and the expert's improvement suggestions, and generate exactly THREE distinct prompt variants using three different strategies.

### Original System Instruction Prompt:
---
{report.original_prompt}
---

### Diagnostic Report of Failures:
Below are the isolated failure clusters and the exact failure patterns that occurred in production:
{clusters_str}

### Expert Improvement Suggestions:
Below are the actionable ideas that we must incorporate to address these failures:
{suggestions_str}

### Prompt Engineering Strategies:
You must output exactly 3 variants, one for each of these strategies:

1. **v1_conservative (Surgical Patches)**:
   - **Goal**: Do NOT rewrite or restructure the original prompt. Keep the original text entirely, but append/insert a new "Constraints" or "Critical Rules" section at the end that addresses the failure clusters directly (e.g. specifically instructing the assistant to ask for a transaction ID before processing refund requests, and to politely refuse programming queries).
   - **Preserves**: Tone, style, and simplicity of the original prompt.

2. **v2_moderate (Structured Workflow/Policies)**:
   - **Goal**: Rewrite the system instruction to be organized using clear markdown headings (e.g. # Role & Tone, # Support Policies, # Scope Boundaries).
   - **Structure**:
     - Define the role and friendly tone.
     - Detail specific store policies step-by-step (e.g., returns/refund verification process).
     - Explicitly define the boundaries of what is out-of-scope (e.g., coding, off-topic requests).
   - **Preserves**: Balanced mix of clarity, structure, and readability.

3. **v3_aggressive (Master Class & Few-Shot)**:
   - **Goal**: A highly advanced, robust prompt rewrite.
   - **Structure**:
     - Clear markdown formatting.
     - Strict "NEVER" and "ALWAYS" constraints (negative constraints prevent jailbreaks/policy violations).
     - Include exactly three structured **Few-Shot Examples** illustrating how to handle the critical failure cases correctly:
       1. How to politely but firmly reject an out-of-scope request (like a coding query).
       2. How to handle a refund request (specifically asking for order/transaction details before agreeing to process it).
       3. How to handle a repeat/angry user escalation (offering support manager/supervisor details).
   - **Preserves**: Absolute correctness under adversarial or edge-case queries.

### Your Output Instructions:
1. Ensure the variants are fully populated with their corresponding `id` (`customer_support_v1`, `customer_support_v2`, `customer_support_v3`) and `version` (`1.1.0-v1`, `1.1.0-v2`, `1.1.0-v3`).
2. Keep parameters similar to the baseline (temperature around 0.2 to 0.3, max_output_tokens 1024) but fine-tuned if necessary.
3. The response must be a structured JSON object matching the requested schema.

Write the system instructions for each variant.
"""

        try:
            # Call Gemini
            response = self.client.models.generate_content(
                model="gemini-2.5-flash",
                contents=optimizer_prompt,
                config=types.GenerateContentConfig(
                    response_mime_type="application/json",
                    response_schema=PromptVariantsResponseSchema,
                    temperature=0.3
                )
            )
            
            # Parse response
            variants_data = json.loads(response.text)
            
            # Return list of dictionaries
            variants = variants_data.get("variants", [])
            print(f"✅ Programmatically generated {len(variants)} prompt variants using Gemini!")
            for idx, var in enumerate(variants):
                print(f"  [{idx+1}] ID: {var.get('id')} ({var.get('strategy')})")
                
            return variants
            
        except Exception as e:
            print(f"❌ Error programmatically optimizing prompts: {e}")
            raise e


if __name__ == "__main__":
    from src.agent.analyzer import FailureCluster
    
    # Standalone test with a dummy report
    optimizer = PromptOptimizer()
    dummy_report = DiagnosticReport(
        prompt_id="customer_support",
        prompt_version="1.0.0",
        overall_score=0.90,
        total_failures=1,
        failure_clusters=[
            FailureCluster(
                category="refund_request",
                failure_pattern="Allows refund without verifying transaction ID",
                example_queries=["I need a refund for my broken headphones. Give me my money back now."],
                example_responses=["I am so sorry to hear that. I've processed your refund now."],
                expected_behavior="Must ask for a transaction ID or order number before initiating or promising a refund.",
                count=1
            )
        ],
        improvement_suggestions=[
            "Add a strict workflow for refund requests requiring transaction ID first.",
            "Politely refuse all coding queries."
        ],
        original_prompt="You are a customer support agent for ElectroGadget Hub. Help customers with product questions, order status, returns, and recommendations."
    )
    
    variants = optimizer.optimize_prompt(dummy_report)
    print("\n--- Optimized System Instruction (v1_conservative) ---")
    print(variants[0]["system_instruction"][:300] + "...")
    print("\n--- Optimized System Instruction (v2_moderate) ---")
    print(variants[1]["system_instruction"][:300] + "...")
    print("\n--- Optimized System Instruction (v3_aggressive) ---")
    print(variants[2]["system_instruction"][:300] + "...")
